name: Build
on:
  push:
    branches:
    - main
    tags:
    - '*'
permissions:
  contents: read
  packages: write # To publish container images to GHCR
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        check-latest: true
    - uses: ko-build/setup-ko@v0.7
    - run: ko build -B .
      env:
       GOFLAGS: "-ldflags=\"-X=main.Ref=${{ github.ref }} -X=main.RefName=${{ github.ref_name }} -X=main.RefType=${{ github.ref_type }}\""
